export const environment = {
    production: false,
    titleWebSite: 'Control Financiero Personal (Dev)',
    paymentsTypeUrl: 'http://localhost:8080/payments/type',
    pocketsUrl: 'http://localhost:8080/pockets',
    cyclesUrl: 'http://localhost:8080/cycles',
    expensesUrl: 'http://localhost:8080/expenses',
    budgetsUrl: 'http://localhost:8080/budgets',
    conceptsUrl: 'http://localhost:8080/concepts',
    incomeUrl: 'http://localhost:8080/api/config/income',
    fixedExpensesUrl: 'http://localhost:8080/api/fixed-expenses',
    pocketsApiUrl: 'http://localhost:8080/api/config/pockets',
    dailyExpensesUrl: 'http://localhost:8080/api/daily-expenses',
    dailyExpensesConfigUrl: 'http://localhost:8080/api/config/daily-budget',
};