export const environment = {
    production: true,
    titleWebSite: 'Control Financiero Personal',
    paymentsTypeUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/payments/type',
    pocketsUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/pockets',
    cyclesUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/cycles',
    expensesUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/expenses',
    budgetsUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/budgets',
    conceptsUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/concepts',
    incomeUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/api/config/income',
    fixedExpensesUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/api/fixed-expenses',
    pocketsApiUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/api/config/pockets',
    dailyExpensesUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/api/daily-expenses',
    dailyExpensesConfigUrl: 'https://expenses-api-dot-quotes-api-100.ue.r.appspot.com/api/config/daily-budget',
};